name = "Untitled"
screen_count = 4
player_start_x = 48.0
player_start_y = 205.0
music_path = ""
music_volume = 0
floor_tile_path = "assets/sprites/levels/grass_tileset.png"
initial_hearts = 0
initial_lives = 0
score_per_life = 0
coin_score = 0

[physics]
walk_max_speed       = 0.0
run_max_speed        = 0.0
walk_ground_accel    = 0.0
run_ground_accel     = 0.0
ground_friction      = 0.0
ground_counter_accel = 0.0
air_accel_walk       = 0.0
air_accel_run        = 0.0
air_friction         = 0.0
cam_lookahead_vx_factor = 0.0
cam_lookahead_max    = 0.0


[last_star]
x = 145.0
y = 167.0

