#!/usr/bin/env python3
"""One source for campaign facts, learning examples and distribution asset size."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from generate_level_catalog import COUNT_GROUPS, total_for
from validate_levels import campaign_manifest_entries

ROOT = Path(__file__).resolve().parents[1]
ASSET_BUDGET = 40 * 1024 * 1024  # Raw playable assets; not compressed transfer size.


def asset_files(root: Path = ROOT) -> list[Path]:
    return sorted(p for p in (root / "assets").rglob("*")
                  if p.is_file() and "unused" not in p.parts
                  and not any(part.startswith(".") for part in p.relative_to(root).parts))


def inventory() -> tuple[dict, str]:
    entries, errors = campaign_manifest_entries()
    if errors:
        raise ValueError("; ".join(errors))
    assets = asset_files()
    total_bytes = sum(p.stat().st_size for p in assets)
    if total_bytes > ASSET_BUDGET:
        raise ValueError(f"playable assets exceed {ASSET_BUDGET} bytes: {total_bytes}")
    facts = {
        "levels": len(entries),
        "screens": sum(data["screen_count"] for _, _, data in entries),
        "labs": len(list((ROOT / "levels/labs").glob("*.toml"))),
        "assetBytes": total_bytes,
        "assetMiB": round(total_bytes / 1024 / 1024, 1),
        "assetBudgetBytes": ASSET_BUDGET,
    }
    for label, keys in COUNT_GROUPS[:3]:
        facts[label.lower()] = sum(total_for(data, keys) for _, _, data in entries)
    text = ["# Asset Inventory", "",
            "> Generated by `tools/content_inventory.py`; run `make content-inventory`.", "",
            f"Playable assets: **{len(assets)} files, {total_bytes:,} bytes**.",
            "Raw-asset budget: **40 MiB**. This is not compressed download size.",
            "Reserve files under `unused/` stay in the source checkout and are excluded from releases.",
            "See [asset provenance](../asset-provenance/) for sources and license status.", "",
            "| Asset | Bytes |", "|-------|------:|"]
    text += [f"| `{p.relative_to(ROOT).as_posix()}` | {p.stat().st_size} |" for p in assets]
    return facts, "\n".join(text) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    facts, markdown = inventory()
    outputs = {ROOT / "docs/src/generated/project.json": json.dumps(facts, indent=2) + "\n",
               ROOT / "docs/wiki/asset-inventory.md": markdown}
    for path, text in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                raise SystemExit(f"stale {path.relative_to(ROOT)}; run make content-inventory")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    print(f"content inventory: ok ({facts['levels']} campaign levels, {facts['labs']} labs, {facts['assetBytes']} asset bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
