#!/usr/bin/env python3
"""
gen_sounds.py — Synthesize every sound effect and ambient loop the game plays.

Every WAV under assets/sounds/ is generated by this file from nothing but
arithmetic, so the audio is original project work covered by the project's
MIT license. Python's standard library is enough: `math` makes waves, `random`
(with fixed seeds) makes noise, `struct` packs samples and `wave` writes the
RIFF header. Running the tool twice produces byte-identical files.

It is also a small lesson in sound synthesis. Read it top to bottom:

    1. A digital sound is a list of numbers ("samples") between -1.0 and +1.0
       played back at a fixed rate. SAMPLE_RATE = 22050 samples per second is
       plenty for retro effects and halves file size versus CD quality (44100).
    2. Oscillators make periodic waves (sine, square, triangle, saw). A *phase
       accumulator* lets pitch change smoothly while the wave plays (sweeps).
    3. Noise is a random value per sample: the raw material of hiss, wind,
       water, splashes and impacts.
    4. Envelopes shape loudness over time. ADSR = Attack, Decay, Sustain,
       Release — the classic synthesizer volume contour.
    5. Filters remove frequencies. A one-pole low-pass filter is a running
       average that keeps rumble and drops hiss; "signal minus its low-pass"
       is a high-pass. Chaining both gives a band-pass.
    6. Mixing is addition; volume is multiplication; normalization scales the
       finished sound so its loudest sample hits a chosen peak in dBFS
       (decibels relative to full scale, where 0 dBFS is the maximum).
    7. Ambient loops must repeat with no click: the tail of a slightly longer
       recording is crossfaded into its head (see loop_crossfade).

Usage:
    python3 tools/gen_sounds.py           # (re)write assets/sounds/**/*.wav
    python3 tools/gen_sounds.py --check   # exit 1 if committed files drift
                                          # (samples may differ by 1 LSB)
    make sounds                           # same as the first form

Output (12 mono 16-bit PCM WAV files, 22050 Hz):
    player/       player_jump, player_hit
    collectibles/ coin
    entities/     bird (wing flap), spider (leap), fish (splash)
    hazards/      axe_trap (whoosh)
    surfaces/     bouncepad (boing)
    screens/      confirm_ui
    levels/       water, lava, winds (seamless ambient loops)
"""

import argparse
import io
import math
import random
import struct
import sys
import wave
from pathlib import Path

# Resolve paths relative to the repo root (the parent of tools/).
REPO_ROOT = Path(__file__).resolve().parents[1]
SOUND_DIR = REPO_ROOT / "assets" / "sounds"

SAMPLE_RATE = 22050   # samples per second (Hz)
TWO_PI = 2.0 * math.pi


def samples(seconds):
    """Convert a duration in seconds to a whole number of samples."""
    return int(round(seconds * SAMPLE_RATE))


# ----------------------------------------------------------------------
# 1. OSCILLATORS — periodic waves with a phase accumulator
# ----------------------------------------------------------------------
#
# "Phase" is how far through one cycle the wave is, from 0.0 to 1.0. Each
# sample advances it by freq / SAMPLE_RATE. Because only the *step* depends on
# the frequency, the frequency may change every sample without the wave
# jumping — that is how pitch sweeps stay smooth.

def wave_shape(shape, phase):
    """Value of one cycle of `shape` at `phase` (0.0 <= phase < 1.0)."""
    if shape == "sine":       # pure tone, no harmonics: soft, flute-like
        return math.sin(TWO_PI * phase)
    if shape == "square":     # odd harmonics: hollow, classic 8-bit "blip"
        return 1.0 if phase < 0.5 else -1.0
    if shape == "triangle":   # weak odd harmonics: rounder than square
        return 4.0 * abs(phase - 0.5) - 1.0
    if shape == "saw":        # all harmonics: bright and buzzy
        return 2.0 * phase - 1.0
    raise ValueError(f"unknown wave shape: {shape}")


def oscillator(shape, freq, n):
    """Render n samples of a wave. `freq` is a number (Hz) or a function
    freq(i) -> Hz evaluated per sample, which allows sweeps and vibrato."""
    freq_at = freq if callable(freq) else (lambda i: freq)
    out = [0.0] * n
    phase = 0.0
    for i in range(n):
        out[i] = wave_shape(shape, phase)
        phase += freq_at(i) / SAMPLE_RATE
        phase -= math.floor(phase)   # wrap back into 0.0 .. 1.0
    return out


def sweep(f_start, f_end, n):
    """Exponential pitch glide from f_start to f_end over n samples.

    Ears hear pitch logarithmically (each octave doubles frequency), so an
    exponential glide sounds even, while a linear one rushes at the low end."""
    span = max(n - 1, 1)
    ratio = f_end / f_start
    return lambda i: f_start * ratio ** (min(i, span) / span)


# ----------------------------------------------------------------------
# 2. NOISE — one random value per sample
# ----------------------------------------------------------------------

def white_noise(n, rng):
    """Equal energy at every frequency: a bright "shhh". `rng` is a seeded
    random.Random so the same seed always yields the same noise."""
    return [rng.uniform(-1.0, 1.0) for _ in range(n)]


def brown_noise(n, rng, leak=0.985):
    """Integrated (summed) white noise: a deep rumble with most energy in the
    bass. The small leak pulls the sum toward zero so it cannot drift away."""
    out = [0.0] * n
    level = 0.0
    for i in range(n):
        level = leak * level + (1.0 - leak) * rng.uniform(-1.0, 1.0) * 4.0
        out[i] = level
    return out


# ----------------------------------------------------------------------
# 3. ENVELOPES — loudness over time
# ----------------------------------------------------------------------

def adsr(n, attack, decay, sustain, release):
    """Linear ADSR contour of n samples (times in seconds, sustain 0..1).

        level
        1.0 |   /\\
            |  /  \\______ sustain
            | /           \\
        0.0 |/             \\
             A   D    S     R   -> time

    The release always ends on the last sample, so the sound fades to zero
    instead of being cut off (a cut produces an audible click)."""
    a, d, r = samples(attack), samples(decay), samples(release)
    out = [0.0] * n
    for i in range(n):
        if i < a:
            level = i / a
        elif i < a + d:
            level = 1.0 - (1.0 - sustain) * (i - a) / d
        else:
            level = sustain
        to_end = n - 1 - i
        if to_end < r:
            level *= to_end / r
        out[i] = level
    return out


def exp_decay(n, half_life, attack=0.002):
    """Short linear attack, then the level halves every `half_life` seconds —
    how struck or plucked things (bells, thuds, drops) die away."""
    a = max(samples(attack), 1)
    k = math.log(2.0) / (half_life * SAMPLE_RATE)
    return [i / a if i < a else math.exp(-k * (i - a)) for i in range(n)]


# ----------------------------------------------------------------------
# 4. FILTERS — one-pole low-pass and friends
# ----------------------------------------------------------------------
#
# y[i] = y[i-1] + alpha * (x[i] - y[i-1])
#
# Each output moves a fraction `alpha` of the way toward the input. Slow
# wiggles (low frequencies) are followed; fast wiggles (high frequencies)
# are smoothed away. alpha is derived from the cutoff frequency in Hz.

def lowpass_alpha(cutoff):
    return 1.0 - math.exp(-TWO_PI * cutoff / SAMPLE_RATE)


def lowpass(x, cutoff):
    """One-pole low-pass. `cutoff` is Hz or a function cutoff(i) -> Hz, so a
    filter can open and close over time (a "filter sweep")."""
    out = [0.0] * len(x)
    y = 0.0
    if callable(cutoff):
        for i, v in enumerate(x):
            y += lowpass_alpha(cutoff(i)) * (v - y)
            out[i] = y
    else:
        alpha = lowpass_alpha(cutoff)
        for i, v in enumerate(x):
            y += alpha * (v - y)
            out[i] = y
    return out


def highpass(x, cutoff):
    """Whatever the low-pass removed: the signal minus its low-pass."""
    return [v - low for v, low in zip(x, lowpass(x, cutoff))]


def bandpass(x, low_cut, high_cut):
    """Keep only the band between low_cut and high_cut Hz."""
    return lowpass(highpass(x, low_cut), high_cut)


# ----------------------------------------------------------------------
# 5. MIXING HELPERS
# ----------------------------------------------------------------------

def multiply(x, y):
    """Sample-by-sample product: applies an envelope or LFO to a signal."""
    return [a * b for a, b in zip(x, y)]


def gain(x, amount):
    return [v * amount for v in x]


def mix_into(dst, src, start, amount=1.0, wrap=False):
    """Add `src` into `dst` starting at sample `start`. With wrap=True the
    part running past the end continues at the beginning — used to place
    events in a loop so a bubble near the seam finishes after the restart."""
    n = len(dst)
    for i, v in enumerate(src):
        j = start + i
        if wrap:
            j %= n
        elif j >= n:
            break
        dst[j] += v * amount


def normalize(x, peak_db):
    """Scale so the loudest sample sits at peak_db dBFS (0 dBFS = full
    scale; -6 dBFS is half the amplitude). Matching peaks keeps sounds from
    different recipes at a consistent level and leaves headroom for mixing."""
    peak = max(abs(v) for v in x)
    target = 10.0 ** (peak_db / 20.0)
    return gain(x, target / peak) if peak > 0.0 else list(x)


# ----------------------------------------------------------------------
# 6. SEAMLESS LOOPS
# ----------------------------------------------------------------------
#
# A loop is heard as ... end, start, end, start ... If the last sample does not
# lead naturally into the first, the player hears a click every repeat.
#
# The trick: render loop_len + fade_len samples of continuous sound. Sample
# loop_len is the natural continuation of sample loop_len - 1, so if the
# *start* of the loop is made to sound like samples loop_len.. (the "tail"),
# the wrap from end to start is seamless. Over the first fade_len samples,
# fade the tail out while fading the head in:
#
#     out[i] = head[i] * fade_in(i) + tail[i] * fade_out(i)
#
# Equal-power curves (sin/cos) keep loudness steady for unrelated noise.
# Anything strictly periodic over the loop (LFOs with a whole number of cycles
# per loop, events placed with wrap=True) is added after this step.

def loop_crossfade(x, loop_len, fade_len):
    assert len(x) >= loop_len + fade_len, "render loop_len + fade_len samples"
    out = list(x[:loop_len])
    for i in range(fade_len):
        t = (i / fade_len) * (math.pi / 2.0)
        out[i] = x[i] * math.sin(t) + x[loop_len + i] * math.cos(t)
    return out


def lfo(n, cycles, phase=0.0):
    """Low Frequency Oscillator: a slow sine (-1..+1) used to move volume or
    a filter. A whole number of `cycles` per loop makes it wrap seamlessly."""
    return [math.sin(TWO_PI * (cycles * i / n + phase)) for i in range(n)]


# ----------------------------------------------------------------------
# 7. SOUND RECIPES — one function per file
# ----------------------------------------------------------------------
#
# Each recipe receives its own seeded random generator and returns a list of
# float samples. Normalization and WAV encoding happen in render().

def bubble(freq, duration):
    """A bubble is a tiny sine "bloop" whose pitch rises as it shrinks."""
    n = samples(duration)
    tone = oscillator("sine", sweep(freq, freq * 1.9, n), n)
    return multiply(tone, exp_decay(n, duration / 4.0, attack=0.003))


def jump_sound(rng):
    """player_jump: a short square-wave blip gliding upward — rising pitch
    reads as "going up"."""
    n = samples(0.16)
    tone = oscillator("square", sweep(260.0, 780.0, n), n)
    tone = lowpass(tone, 3500.0)          # soften the harsh square edges
    return multiply(tone, adsr(n, 0.003, 0.05, 0.55, 0.07))


def hit_sound(rng):
    """player_hit: a descending triangle "thud" plus a noise burst whose
    filter closes quickly — a dull impact, falling pitch reads as "ouch"."""
    n = samples(0.35)
    body = oscillator("triangle", sweep(320.0, 55.0, n), n)
    body = multiply(body, exp_decay(n, 0.08))
    crunch = lowpass(white_noise(n, rng), sweep(4000.0, 300.0, n))
    crunch = multiply(crunch, exp_decay(n, 0.035))
    out = [0.75 * b + 1.6 * c for b, c in zip(body, crunch)]
    return multiply(out, adsr(n, 0.0, 0.0, 1.0, 0.05))   # clean ending


def coin_sound(rng):
    """coin: a two-tone chime, B5 then E6 (a rising fourth). A sine plus a
    quieter second harmonic and an exponential decay sounds bell-like."""
    def chime(freq, n, half_life):
        tone = [a + 0.3 * b for a, b in zip(oscillator("sine", freq, n),
                                            oscillator("sine", freq * 2.0, n))]
        return multiply(tone, exp_decay(n, half_life))

    out = [0.0] * samples(0.50)
    first = chime(987.77, samples(0.07), 0.04)       # B5, cut short ...
    first = multiply(first, adsr(len(first), 0.0, 0.0, 1.0, 0.01))
    mix_into(out, first, 0)
    mix_into(out, chime(1318.51, samples(0.43), 0.08), samples(0.07))  # ... E6 rings
    tail = adsr(len(out), 0.0, 0.0, 1.0, 0.05)       # guarantee a clean end
    return multiply(out, tail)


def flap_sound(rng):
    """bird: a wing flap — two soft band-passed noise puffs (down-stroke,
    then a weaker up-stroke). Plays every flap cycle, so it stays subtle."""
    out = [0.0] * samples(0.22)
    for start, amount in ((0.0, 1.0), (0.09, 0.6)):
        n = samples(0.10)
        puff = bandpass(white_noise(n, rng), 400.0, 2200.0)
        puff = multiply(puff, adsr(n, 0.015, 0.03, 0.4, 0.05))
        mix_into(out, puff, samples(start), amount)
    return out


def spider_sound(rng):
    """spider: a leap — a quick hiss (high band of noise) over a rising
    triangle "zip", plus a few skittering clicks of legs pushing off."""
    n = samples(0.30)
    hiss = bandpass(white_noise(n, rng), 2500.0, 7000.0)
    hiss = multiply(hiss, adsr(n, 0.01, 0.08, 0.3, 0.15))
    zip_n = samples(0.10)
    zip_tone = oscillator("triangle", sweep(300.0, 900.0, zip_n), zip_n)
    zip_tone = multiply(zip_tone, adsr(zip_n, 0.005, 0.03, 0.5, 0.04))
    out = gain(hiss, 2.0)
    mix_into(out, zip_tone, 0, 0.35)
    for at in (0.0, 0.03, 0.055, 0.075):
        click_n = samples(0.004)
        click = multiply(highpass(white_noise(click_n, rng), 1500.0),
                         exp_decay(click_n, 0.001, attack=0.0005))
        mix_into(out, click, samples(at), 0.8)
    return out


def splash_sound(rng):
    """fish: falling into water — a noise burst whose low-pass closes from
    bright to dull (the splash), then a scatter of rising bubbles."""
    n = samples(0.90)
    splash_n = samples(0.40)
    splash = lowpass(white_noise(splash_n, rng), sweep(6000.0, 400.0, splash_n))
    splash = multiply(splash, exp_decay(splash_n, 0.07, attack=0.005))
    out = [0.0] * n
    mix_into(out, gain(splash, 1.5), 0)
    for k in range(10):
        start = 0.08 + rng.random() * 0.62
        freq = 300.0 + rng.random() * 600.0
        duration = 0.04 + rng.random() * 0.05
        fade = 1.0 - 0.7 * (start / 0.75)            # later bubbles quieter
        mix_into(out, bubble(freq, duration), samples(start), 0.45 * fade)
    return multiply(out, adsr(n, 0.0, 0.0, 1.0, 0.05))


def axe_sound(rng):
    """axe_trap: a whoosh — noise through a filter that opens then closes
    while the volume swells and fades, like a blade passing by."""
    n = samples(0.45)
    swell = [math.sin(math.pi * i / (n - 1)) for i in range(n)]   # 0 -> 1 -> 0
    noise = highpass(white_noise(n, rng), 200.0)
    noise = lowpass(noise, lambda i: 300.0 + 2200.0 * swell[i])
    return multiply(noise, [s * s for s in swell])


def bouncepad_sound(rng):
    """bouncepad: a cartoon "boing" — a sine whose pitch springs upward and
    then wobbles (vibrato) while the wobble and volume die away."""
    n = samples(0.50)
    rise = sweep(140.0, 420.0, samples(0.12))

    def freq(i):
        t = i / SAMPLE_RATE
        depth = 0.12 * math.exp(-t * 5.0)               # vibrato fades out
        return rise(i) * (1.0 + depth * math.sin(TWO_PI * 14.0 * t))

    tone = [a + 0.3 * b for a, b in zip(oscillator("sine", freq, n),
                                        oscillator("triangle", freq, n))]
    env = multiply(exp_decay(n, 0.12, attack=0.003), adsr(n, 0.0, 0.0, 1.0, 0.04))
    return multiply(tone, env)


def confirm_sound(rng):
    """confirm_ui: two quick square blips, E5 then B5 — a bright "OK"."""
    out = [0.0] * samples(0.22)
    for start, freq, length in ((0.0, 659.25, 0.07), (0.08, 987.77, 0.14)):
        n = samples(length)
        blip = oscillator("square", freq, n)
        blip = multiply(lowpass(blip, 4000.0), adsr(n, 0.002, 0.03, 0.6, 0.04))
        mix_into(out, blip, samples(start))
    return out


LOOP_FADE = 0.5   # seconds of tail crossfaded into the head of each loop


def water_loop(rng):
    """water: lapping water — a low "wash" and a soft surf hiss, both
    filtered noise, swelling with two slow LFOs, plus occasional bubbles."""
    loop_n, fade_n = samples(6.0), samples(LOOP_FADE)
    raw = white_noise(loop_n + fade_n, rng)
    wash = lowpass(raw, 250.0)
    surf = bandpass(raw, 300.0, 1400.0)
    bed = loop_crossfade([2.5 * w + 0.6 * s for w, s in zip(wash, surf)],
                         loop_n, fade_n)
    slow, faster = lfo(loop_n, 2), lfo(loop_n, 5, phase=0.3)
    out = [v * (0.6 + 0.25 * a + 0.15 * b) for v, a, b in zip(bed, slow, faster)]
    for k in range(6):
        bubble_sound = bubble(250.0 + rng.random() * 350.0, 0.05 + rng.random() * 0.05)
        mix_into(out, bubble_sound, int(rng.random() * loop_n), 0.12, wrap=True)
    return out


def lava_loop(rng):
    """lava: a deep rumble (low-passed brown noise) with a faint sizzle on
    top, slow "blorp" bubbles and a few crackling pops."""
    loop_n, fade_n = samples(6.0), samples(LOOP_FADE)
    rumble = highpass(lowpass(brown_noise(loop_n + fade_n, rng), 120.0), 25.0)
    sizzle = bandpass(white_noise(loop_n + fade_n, rng), 1500.0, 4000.0)
    bed = loop_crossfade([4.0 * r + 0.08 * s for r, s in zip(rumble, sizzle)],
                         loop_n, fade_n)
    swell = lfo(loop_n, 1)
    out = [v * (0.75 + 0.25 * s) for v, s in zip(bed, swell)]
    for k in range(7):                       # big, slow lava bubbles
        length = samples(0.12 + rng.random() * 0.13)
        blorp = oscillator("sine", sweep(70.0, 180.0 + rng.random() * 60.0, length), length)
        blorp = multiply(blorp, adsr(length, 0.02, 0.04, 0.6, 0.06))
        mix_into(out, blorp, int(rng.random() * loop_n), 0.35, wrap=True)
    for k in range(12):                      # tiny crackles
        pop_n = samples(0.003)
        pop = multiply(highpass(white_noise(pop_n, rng), 2000.0),
                       exp_decay(pop_n, 0.0008, attack=0.0003))
        mix_into(out, pop, int(rng.random() * loop_n), 0.25, wrap=True)
    return out


def winds_loop(rng):
    """winds: band-limited noise whose band drifts up and down while its
    volume swells in slow gusts. The filter LFO has a whole number of cycles
    per loop, so the tail and head are filtered alike before the crossfade."""
    loop_n, fade_n = samples(8.0), samples(LOOP_FADE)
    total = loop_n + fade_n
    drift = [math.sin(TWO_PI * 2.0 * i / loop_n) for i in range(total)]
    noise = highpass(white_noise(total, rng), lambda i: 350.0 + 150.0 * drift[i])
    noise = lowpass(noise, lambda i: 1100.0 + 600.0 * drift[i])
    bed = loop_crossfade(noise, loop_n, fade_n)
    gusts, flutter = lfo(loop_n, 2, phase=0.75), lfo(loop_n, 7)
    return [v * (0.55 + 0.35 * g + 0.1 * f) for v, g, f in zip(bed, gusts, flutter)]


# (path under assets/sounds/, recipe, seed, peak dBFS)
# Peak is not loudness: a short noise burst reaches its peak only briefly, while
# a square wave sits at its peak the whole time. So noisy SFX peak at -3 dBFS,
# tonal ones lower and square blips lowest, which keeps their average (RMS)
# levels close together. Ambience sits below the effects; each level's
# music_volume then scales it further.
SOUNDS = [
    ("player/player_jump.wav",     jump_sound,      101, -11.0),
    ("player/player_hit.wav",      hit_sound,       102, -3.0),
    ("collectibles/coin.wav",      coin_sound,      103, -5.0),
    ("entities/bird.wav",          flap_sound,      104, -6.0),
    ("entities/spider.wav",        spider_sound,    105, -5.0),
    ("entities/fish.wav",          splash_sound,    106, -3.0),
    ("hazards/axe_trap.wav",       axe_sound,       107, -3.0),
    ("surfaces/bouncepad.wav",     bouncepad_sound, 108, -5.0),
    ("screens/confirm_ui.wav",     confirm_sound,   109, -11.0),
    ("levels/water.wav",           water_loop,      201, -9.0),
    ("levels/lava.wav",            lava_loop,       202, -9.0),
    ("levels/winds.wav",           winds_loop,      203, -9.0),
]


# ----------------------------------------------------------------------
# 8. WAV ENCODING
# ----------------------------------------------------------------------

def encode_wav(signal):
    """Pack floats as mono 16-bit PCM: each sample becomes a little-endian
    signed integer in -32767..32767. The `wave` module writes no timestamps,
    so identical samples always give identical bytes."""
    ints = [max(-32767, min(32767, int(round(v * 32767.0)))) for v in signal]
    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as out:
        out.setnchannels(1)
        out.setsampwidth(2)
        out.setframerate(SAMPLE_RATE)
        out.writeframes(struct.pack(f"<{len(ints)}h", *ints))
    return buffer.getvalue()


def render(recipe, seed, peak_db):
    """Run one recipe with its own seeded generator and encode the result."""
    return encode_wav(normalize(recipe(random.Random(seed)), peak_db))


def render_all():
    """Return {relative path: WAV bytes} for every sound, in table order."""
    return {path: render(recipe, seed, peak) for path, recipe, seed, peak in SOUNDS}


# Python's math.sin/math.exp/** call the platform C library (libm). macOS and
# Linux may disagree in the last ulp (unit in the last place) of a result, and
# such a tiny difference can flip how a sample rounds to int16. Writing stays
# deterministic on any one platform; --check therefore accepts a difference of
# at most 1 LSB per sample, while the header and frame count must match exactly.
SAMPLE_TOLERANCE = 1


def wav_matches(committed, generated, tolerance=SAMPLE_TOLERANCE):
    """True if two 16-bit mono WAVs have identical headers and frame counts and
    every sample differs by at most `tolerance` (in int16 steps)."""
    try:
        with wave.open(io.BytesIO(committed)) as a, wave.open(io.BytesIO(generated)) as b:
            if a.getparams() != b.getparams() or a.getsampwidth() != 2:
                return False
            frames = a.getnframes() * a.getnchannels()
            pcm_a = struct.unpack(f"<{frames}h", a.readframes(a.getnframes()))
            pcm_b = struct.unpack(f"<{frames}h", b.readframes(b.getnframes()))
    except (wave.Error, EOFError, struct.error):
        return False
    header = len(generated) - 2 * frames      # bytes before the sample data
    if len(committed) != len(generated) or committed[:header] != generated[:header]:
        return False
    return all(abs(x - y) <= tolerance for x, y in zip(pcm_a, pcm_b))


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate assets/sounds/ WAV files.")
    parser.add_argument("--check", action="store_true",
                        help="compare regenerated sounds with committed files "
                             "(exact header, samples within 1 LSB); do not write")
    args = parser.parse_args(argv)
    rendered = render_all()

    if args.check:
        problems = []
        for path, data in rendered.items():
            target = SOUND_DIR / path
            if not target.is_file():
                problems.append(f"missing assets/sounds/{path}")
            elif not wav_matches(target.read_bytes(), data):
                problems.append(f"drift in assets/sounds/{path}")
        # Every shipped sound must come from this generator (licensing).
        extra = sorted(p.relative_to(SOUND_DIR).as_posix()
                       for p in SOUND_DIR.rglob("*.wav")
                       if p.relative_to(SOUND_DIR).as_posix() not in rendered)
        problems += [f"assets/sounds/{p} is not produced by tools/gen_sounds.py"
                     for p in extra]
        if problems:
            for problem in problems:
                print(f"gen_sounds: {problem}", file=sys.stderr)
            print("gen_sounds: run `make sounds` to regenerate", file=sys.stderr)
            return 1
        print(f"gen_sounds: ok ({len(rendered)} files, "
              f"{sum(map(len, rendered.values()))} bytes)")
        return 0

    for path, data in rendered.items():
        target = SOUND_DIR / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        print(f"  {path} ({len(data)} bytes)")
    print(f"=== Done! {len(rendered)} sounds, {sum(map(len, rendered.values()))} bytes ===")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
