#!/usr/bin/env python3
"""Generate checked text snapshots for runtime overlays."""

from __future__ import annotations

from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "render" / "render_overlay.c"
OUT = ROOT / "docs" / "wiki" / "overlay-snapshots.md"


def text_tokens(block: str) -> list[str]:
    tokens = re.findall(r'render_centered_text\([^;]*?"([^"]+)"', block, re.S)
    for left, right in re.findall(r'\?\s*"([^"]+)"\s*:\s*"([^"]+)"', block):
        tokens.extend([left, right])
    tokens.extend(re.findall(r'snprintf\([^;]*?"([^"]+)"', block, re.S))
    return sorted(set(tokens))


def overlay_blocks() -> dict[str, list[str]]:
    source = SOURCE.read_text(encoding="utf-8")
    starts = list(re.finditer(r'void\s+(render_[a-z_]+_overlay)\s*\(GameState \*gs\)\s*\{', source))
    blocks: dict[str, list[str]] = {}
    for index, match in enumerate(starts):
        end = starts[index + 1].start() if index + 1 < len(starts) else len(source)
        blocks[match.group(1)] = text_tokens(source[match.start():end])
    return blocks


def render() -> str:
    blocks = overlay_blocks()
    all_tokens = sorted({token for tokens in blocks.values() for token in tokens})
    lines = [
        "# Overlay Text Snapshots",
        "",
        "Generated by `tools/generate_overlay_snapshots.py` from `src/render/render_overlay.c`.",
        "Run `make overlay-snapshots` to refresh and `make docs-drift` to check drift.",
        "",
        "These source-derived snapshots keep user-facing overlay copy auditable even before",
        "true pixel golden-image testing is available.",
        "",
        "## Source tokens",
        "",
    ]
    for token in all_tokens:
        lines.append(f"- `{token}`")
    lines.extend(["", "## Overlay function snapshots", ""])
    for name in sorted(blocks):
        title = name.replace("render_", "").replace("_overlay", "").replace("_", " ").title()
        lines.extend([f"### {title}", ""])
        for token in blocks[name]:
            lines.append(f"- `{token}`")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if snapshots are stale")
    args = parser.parse_args()

    text = render()
    if OUT.exists() and OUT.read_text(encoding="utf-8") == text:
        print("overlay snapshots: ok")
        return 0
    if args.check:
        print(f"overlay snapshots: stale; run `make overlay-snapshots` to refresh {OUT.relative_to(ROOT)}")
        return 1
    OUT.write_text(text, encoding="utf-8")
    print(f"overlay snapshots: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
