#!/usr/bin/env python3
"""Generate docs/wiki/level-catalog.md from levels/*.toml.

The catalog is intentionally derived from the same TOML files loaded by the game
so docs can advertise level content without hand-maintained counts drifting.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - CI uses Python 3.11+
    sys.stderr.write("generate_level_catalog: Python 3.11+ required for tomllib\n")
    sys.exit(2)

ROOT = Path(__file__).resolve().parents[1]
LEVEL_DIR = ROOT / "levels"
OUTPUT = ROOT / "docs" / "wiki" / "level-catalog.md"

COUNT_GROUPS = [
    ("Enemies", ["spiders", "jumping_spiders", "birds", "faster_birds", "fish", "faster_fish"]),
    ("Hazards", ["spike_rows", "spike_blocks", "spike_platforms", "circular_saws", "axe_traps", "blue_flames", "fire_flames"]),
    ("Collectibles", ["coins", "star_yellows", "star_greens", "star_reds", "last_star"]),
    ("Surfaces", ["platforms", "float_platforms", "bridges", "bouncepads_small", "bouncepads_medium", "bouncepads_high", "vines", "ladders", "ropes", "rails"]),
    ("Visual layers", ["background_layers", "foreground_layers", "fog_layers"]),
]


def load_level(path: Path) -> dict:
    with path.open("rb") as fp:
        return tomllib.load(fp)


def count_value(value) -> int:
    if isinstance(value, list):
        return len(value)
    if isinstance(value, dict):
        return 1
    return 0


def total_for(data: dict, keys: list[str]) -> int:
    return sum(count_value(data.get(key)) for key in keys)


def md_text(value) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def code_text(value) -> str:
    return str(value).replace("`", "\\`")


def next_phase_for(data: dict) -> str:
    last_star = data.get("last_star")
    if isinstance(last_star, dict):
        return str(last_star.get("next_phase") or "")
    return ""


def single_line_description(data: dict) -> str:
    raw = str(data.get("description", "")).strip()
    if not raw:
        return "—"
    first = " ".join(line.strip() for line in raw.splitlines() if line.strip())
    return md_text(first)


def md_link(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    return f"[`{rel}`](https://github.com/jonathanperis/super-mango-editor/blob/main/{rel})"


def render_level(path: Path, data: dict) -> list[str]:
    name = md_text(data.get("name") or path.stem)
    next_phase = next_phase_for(data)
    next_value = f"`{code_text(next_phase)}`" if next_phase else "—"
    lines = [
        f"### {name}",
        "",
        f"- **File:** {md_link(path)}",
        f"- **Generated by:** {md_text(data.get('generated_by', '—'))}",
        f"- **Screens:** {data.get('screen_count', '—')}",
        f"- **Player start:** `{code_text(data.get('player_start_x', '—'))}, {code_text(data.get('player_start_y', '—'))}`",
        f"- **Music:** `{code_text(data.get('music_path', '—'))}` at volume `{code_text(data.get('music_volume', '—'))}`",
        f"- **Floor tiles:** `{code_text(data.get('floor_tile_path', '—'))}`",
        f"- **Initial hearts/lives:** `{code_text(data.get('initial_hearts', '—'))}` / `{code_text(data.get('initial_lives', '—'))}`",
        f"- **Next phase:** {next_value}",
        "",
        single_line_description(data),
        "",
        "| Group | Count | Included TOML arrays |",
        "|-------|------:|----------------------|",
    ]
    for label, keys in COUNT_GROUPS:
        present_keys = [key for key in keys if count_value(data.get(key))]
        included = ", ".join(f"`{key}`" for key in present_keys) if present_keys else "—"
        lines.append(f"| {label} | {total_for(data, keys)} | {included} |")
    lines.append("")
    return lines


def render_catalog() -> str:
    levels = sorted(LEVEL_DIR.glob("*.toml"))
    loaded = [(path, load_level(path)) for path in levels]
    total_screens = sum(int(data.get("screen_count", 0)) for _, data in loaded)
    total_collectibles = sum(total_for(data, COUNT_GROUPS[2][1]) for _, data in loaded)
    total_hazards = sum(total_for(data, COUNT_GROUPS[1][1]) for _, data in loaded)
    total_enemies = sum(total_for(data, COUNT_GROUPS[0][1]) for _, data in loaded)

    lines = [
        "# Level Catalog",
        "",
        "> Generated from `levels/*.toml` by `tools/generate_level_catalog.py`. Do not hand-edit counts; run `make level-catalog` after changing levels.",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|------:|",
        f"| Levels | {len(loaded)} |",
        f"| Screens | {total_screens} |",
        f"| Enemies | {total_enemies} |",
        f"| Hazards | {total_hazards} |",
        f"| Collectibles | {total_collectibles} |",
        "",
        "## Level progression",
        "",
        "| Level | Screens | Music | Next phase |",
        "|-------|--------:|-------|------------|",
    ]
    for path, data in loaded:
        name = md_text(data.get("name") or path.stem)
        next_phase = next_phase_for(data)
        next_value = f"`{code_text(next_phase)}`" if next_phase else "—"
        lines.append(
            f"| {name} | {data.get('screen_count', '—')} | `{code_text(data.get('music_path', '—'))}` | {next_value} |"
        )
    lines.extend(["", "## Per-level details", ""])
    for path, data in loaded:
        lines.extend(render_level(path, data))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed catalog is stale")
    args = parser.parse_args()

    rendered = render_catalog()
    if args.check:
        if not OUTPUT.exists():
            print(f"level catalog missing: {OUTPUT.relative_to(ROOT)}")
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != rendered:
            print("level catalog is stale; run `make level-catalog`")
            return 1
        print("level catalog: ok")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
